# Generated by Django 4.2.2 on 2023-06-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('due_date', models.DateField()),
                ('state', models.CharField(choices=[('C', 'Created'), ('P', 'In Progress'), ('D', 'Done')], max_length=1)),
            ],
            options={
                'ordering': ('due_date',),
            },
        ),
    ]
